services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./data:/import # Map the data folder to neo4j's import folder
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_server_directories_import=/import
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always
    logging:
      driver: "none"

volumes:
  db-data:
  pgadmin:
