-- Basic `SELECT` with simple `WHERE` clause.

SELECT 
    B_Title,
    B_PUBLISHER,
    B_PUBLISH_DATE,
    B_ISBN13,
    B_DESCRIPTION,
    B_PAGE_COUNT,
    B_LANGUAGE
FROM Book
WHERE B_PUBLISH_DATE >= '2010-01-01' AND B_PUBLISH_DATE < '2020-01-01'
ORDER BY B_PUBLISH_DATE DESC;